use_frameworks!

platform :ios, '8.0'

target 'KZWRouter_Example' do
  pod 'KZWRouter', :path => '../'
  pod 'KZWWebViewController_Category'
  pod 'KZWWebViewController'

  target 'KZWRouter_Tests' do
    inherit! :search_paths
  end
end
